version: '3.5'
services:
  application-api:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET=${JWT_SECRET}
        - CORS_ORIGINS=${CORS_ORIGINS}
        - PORT=${PORT}
        - LAUNCH_SECRET=${LAUNCH_SECRET}
        - USERS_API_URL=${USERS_API_URL}
    ports:
      - '80:8080'
    networks:
      - siifweb-network

networks:
  siifweb-network:
    name: siifweb-network
